apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animals
      service: web
  template:
    metadata:
      labels:
        app: animals
        service: web
    spec:
      containers:
      - image: 126689273402.dkr.ecr.eu-north-1.amazonaws.com/pets:web
        name: web
        ports:
        - containerPort: 3000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: animals
    service: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animals
      service: db
  template:
    metadata:
      labels:
        app: animals
        service: db
    spec:
      containers:
      - name: db
        image: 126689273402.dkr.ecr.eu-north-1.amazonaws.com/pets:db
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: animals
    service: db